name: Add Godlike Server Time

on:
  schedule:
    - cron: "*/30 * * * *"  # 每30分钟触发一次
  workflow_dispatch:        # 允许手动触发

jobs:
  add_time_job:
    runs-on: ubuntu-latest
    
    # 由于脚本现在是单次运行，不再需要长时间的 timeout
    # 设置一个合理的超时，例如10分钟，防止意外卡死
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Playwright and dependencies
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Run Time Adder Script
        env:
          PTERODACTYL_COOKIE: ${{ secrets.PTERODACTYL_COOKIE }}
          PTERODACTYL_EMAIL: ${{ secrets.PTERODACTYL_EMAIL }}
          PTERODACTYL_PASSWORD: ${{ secrets.PTERODACTYL_PASSWORD }}
        # 使用 -u 参数禁用输出缓冲，确保日志实时显示
        run: python -u main.py

      - name: Upload error artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshots
          path: "*.png"
